### ISSUE TITLE
can't access the classes

### ISSUE THREAD

**Issue by caofei10119** [mfornos/humanize#33]
I installed this library using grandle compile group:'com.github.mfornos', name:'humanize', version:'1.2.2'
and it compiled successfully but I can't access humanize class
what could be the problem?

**Comment by mfornos** [comment]
Try with 'com.github.mfornos:humanize-slim:1.2.2'

Hope this helps.

**Comment by caofei10119** [comment]
yes, it works thanks a lot

**Comment by caofei10119** [comment]
Do you have any idea why maven is not working?

**Comment by mfornos** [comment]
This declaration should work:
```xml
<dependency>
	<groupId>com.github.mfornos</groupId>
	<artifactId>humanize-slim</artifactId>
	<version>1.2.2</version>
</dependency>
```

Cheers!

**Comment by caofei10119** [comment]
Is it correct 'com.github.mfornos:humanize-slim:1.2.2' for icu?

**Comment by mfornos** [comment]
Yes, but you should use the class `humanize.ICUHumanize` as facade instead of `humanize.Humanize`.
