### ISSUE TITLE
Missing Resource Exception

### ISSUE THREAD

**Issue by subediaayush** [mfornos/humanize#35]
I get a java.util.MissingResourceException when trying to run this 

`String NewString = naturalDay(date);`

Is there something I am missing or something I need to do before calling `naturalDay`?

**Comment by mfornos** [comment]
Seems that your locale is not supported. I will open an issue to add meaningful exception for this error case.

If you want you can support your language just adding a file named `Humanize_{your_locale}.properties` into a folder named `i18n` accesible from the classpath.
The content must be the same as in: https://github.com/mfornos/humanize/blob/master/humanize-slim/src/main/resources/i18n/Humanize_en.properties (but for your locale).

Thank you
