### ISSUE TITLE
Gradle/Jitpack support

### ISSUE THREAD

**Issue by ahaverty** [mfornos/humanize#37]
Jitpack'd your repo for android. Might be worth adding jitpack to the readme for gradle users?
All automatic per release or current -Snapshot.

**E.G:**

    compile 'com.github.mfornos.humanize:humanize:humanize-1.2.2'
**OR**

    compile 'com.github.mfornos.humanize:humanize:-SNAPSHOT'
**for the latest commit**

## Image / jitpack URL

Link:
`[![](https://jitpack.io/v/mfornos/humanize.svg)](https://jitpack.io/#mfornos/humanize)`

[![](https://jitpack.io/v/mfornos/humanize.svg)](https://jitpack.io/#mfornos/humanize)

**Comment by ahaverty** [comment]
Sorry, scrap that^.
I was able to import using gradle: 
```
compile ('com.github.mfornos:humanize-icu:1.2.2'){
        exclude group: 'com.google.code.findbugs'
    }
```
But I had to exclude that group as I was running into the following error:
`Conflict with dependency 'com.google.code.findbugs:jsr305'. Resolved versions for app and test app differ.`
I will close this issue if you'd like. Thanks for a great repo!

**Comment by mfornos** [comment]
Thank you very much! :)
